# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ModzyCli < Formula
  desc "Repository of Modzy Util taps"
  homepage "https://github.com/modzy/homebrew-tap"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/modzy/cli/releases/download/v1.0.0/modzy-cli_1.0.0_Darwin_arm64.tar.gz"
      sha256 "31c32ca667ccb168d3b55c1babbf0bd84d89f8b995d5e74d252c92ffafd0c6bd"

      def install
        bin.install "modzy-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/modzy/cli/releases/download/v1.0.0/modzy-cli_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "3b1ee2fcf05df6e9a082a262a6e0330ff2927d5fa2ed3f6a3a7fc9183e8182ae"

      def install
        bin.install "modzy-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/modzy/cli/releases/download/v1.0.0/modzy-cli_1.0.0_Linux_arm64.tar.gz"
      sha256 "051400a6afcbd5c8a3cc21e42ef28a4f69299c5a70e16963ac564f857d80d6aa"

      def install
        bin.install "modzy-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/modzy/cli/releases/download/v1.0.0/modzy-cli_1.0.0_Linux_x86_64.tar.gz"
      sha256 "a523326c080271c316d3c7543680f0b2fe1c246975d542b9c53c6d2cebb7a21b"

      def install
        bin.install "modzy-cli"
      end
    end
  end
end
